version: "3.8"

services:
    nginx:
        build: ./docker/nginx
        container_name: "nginx"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/app
        depends_on:
            - python
        networks:
            - schoolplus-network
    python:
        build:
            context: ./
            dockerfile: ./docker/python/Dockerfile
        container_name: "python"
        volumes:
            - .:/app
        depends_on:
            - database
        networks:
            - schoolplus-network
    database:
        image: mysql:8.0.24
        container_name: "database"
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        networks:
            - schoolplus-network

networks:
  schoolplus-network:
    name: schoolplus-network
    driver: bridge
