# Generated by Django 3.2.2 on 2021-05-10 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('created', models.DateField(null=True, verbose_name='created')),
                ('deleted', models.DateField(db_index=True, null=True, verbose_name='deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('created', models.DateField(null=True, verbose_name='created')),
                ('deleted', models.DateField(db_index=True, null=True, verbose_name='deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('birthdate', models.DateField(null=True, verbose_name='birthdate')),
                ('rg', models.CharField(max_length=14, null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('created', models.DateField(null=True, verbose_name='created')),
                ('deleted', models.DateField(db_index=True, null=True, verbose_name='deleted')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('birthdate', models.DateField(null=True, verbose_name='birthdate')),
                ('rg', models.CharField(max_length=14, null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('created', models.DateField(null=True, verbose_name='created')),
                ('deleted', models.DateField(db_index=True, null=True, verbose_name='deleted')),
                ('classrooms', models.ManyToManyField(to='api.ClassRoom')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grade')),
            ],
        ),
    ]
